# -*- coding: utf-8 -*-
"""Float.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K25LRMpMsLmDcYX0w0RjkSPBSNgFLfO0
"""

# SOLVED EXAMPLE
# --------------
# Question: Calculate the area of a circle with radius 5.5
print("SOLVED EXAMPLE:")
print("Calculate the area of a circle with radius 5.5")
import math
radius = 5.5
area = math.pi * radius ** 2
print(f"Radius: {radius}")
print(f"Area: {area:.2f}")

# ASSIGNMENT QUESTIONS
# ===================

# Question 1: Calculate the average of 3.14, 2.718, 1.618, 0.577
print("Question 1: Calculate the average of 3.14, 2.718, 1.618, 0.577")
# Your code here
numbers=[3.14,2.718,1.618,0.577]
average=sum(numbers)/len(numbers)
print(f"The average of numbers: {numbers} is {average:.2f}")

#Question 2: Convert 98.6 Fahrenheit to Celsius (F = C * 9/5 + 32)
print("\nQuestion 2: Convert 98.6 Fahrenheit to Celsius")
# Your code here
fahrenheit=98.6
celsius=(fahrenheit - 32)*5/9
print(f"{fahrenheit} Fahrenheit is equal to {celsius:.2f} Celsius")

# Question 3: Calculate the compound interest on $1000 at 5.5% for 3 years
print("\nQuestion 3: Calculate compound interest on $1000 at 5.5% for 3 years")
# Your code here
principal = 1000
rate = 0.055
time = 3
amount = principal * (1 + rate) ** time
interest = amount - principal
print(f"Principal: ${principal}")
print(f"Rate: {rate * 100}%")
print(f"Time: {time} years")
print(f"Amount: ${amount:.2f}")
print(f"Interest: ${interest:.2f}")

#Question 4: Find the hypotenuse of a right triangle with sides 3.5 and 4.2
print("\nQuestion 4: Find the hypotenuse of a right triangle with sides 3.5 and 4.2")
# Your code here
side1 = 3.5
side2 = 4.2
hypotenuse = math.sqrt(side1**2 + side2**2)
print(f"Side 1: {side1}")
print(f"Side 2: {side2}")
print(f"Hypotenuse: {hypotenuse:.2f}")

# Question 5: Calculate the volume of a sphere with radius 7.8
print("\nQuestion 5: Calculate the volume of a sphere with radius 7.8")
# Your code here
radius = 7.8
volume = (4/3) * math.pi * radius**3
print(f"Radius: {radius}")
print(f"Volume: {volume:.2f}")

# Question 6: Round 3.14159 to 3 decimal places
print("\nQuestion 6: Round 3.14159 to 3 decimal places")
# Your code here
number = 3.14159
rounded_number = round(number, 3)
print(f"Number: {number}")
print(f"Rounded number: {rounded_number}")

# Question 7: Calculate the percentage: 45 out of 67
print("\nQuestion 7: Calculate the percentage: 45 out of 67")
# Your code here
numerator = 45
denominator = 67
percentage = (numerator / denominator) * 100
print(f"Numerator: {numerator}")
print(f"Denominator: {denominator}")
print(f"Percentage: {percentage:.2f}%")
print("-" * 50)

# Question 8: Find the square root of 23.456
print("\nQuestion 8: Find the square root of 23.456")
# Your code here
number = 23.456
square_root = math.sqrt(number)
print(f"Number: {number}")
print(f"Square root: {square_root:.2f}")

# Question 9: Calculate the simple interest: Principal=2500, Rate=6.5%, Time=2.5 years
print("\nQuestion 9: Calculate simple interest: Principal=2500, Rate=6.5%, Time=2.5 years")
# Your code here
principal = 2500
Rate = 0.065
Time = 2.5
interest = principal * Rate * Time
amount = principal + interest
print(f"Principal: ${principal}")
print(f"Rate: {Rate * 100}%")
print(f"Time: {Time} years")
print(f"Amount: ${amount:.2f}")
print(f"Interest: ${interest:.2f}")

# Question 10: Convert 45.7 degrees to radians
print("\nQuestion 10: Convert 45.7 degrees to radians")
# Your code here
degrees = 45.7
radians = degrees * (math.pi / 180)
print(f"{degrees} degrees is equal to {radians:.2f} radians")