# -*- coding: utf-8 -*-
"""Integer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-S-YVKvAUuD650GagZ6i-mImWLkUCKP
"""

# Question 1: Calculate the product of first 10 natural numbers
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
import math
print(math.prod(nums))

# Question 2: Find the remainder when 156 is divided by 7
num = 156
div = 7
remainder = num % div
print(f"remainder is =", remainder)

# Question 3: Calculate the square of 25
num = 25
power = 2
square = pow(num,power)
print(square)

# Question 4: Find the cube root of 125
num = 125
cube = pow(num,1/3)
print(cube)

# Question 5: Calculate the sum of digits in number 12345
num = 12345
sum = 0

for i in str(num):
    sum += int(i)
print(sum)

# Question 6: Check if 97 is a prime number
num = 97
is_prime = True


for i in range(2, num):
    if num % i == 0:
        is_prime = False
        break

if is_prime:
    print("prime number")

else:
    print("not a prime number")

# Question 7: Find the factorial of 8
num = 8
fact = 1
for i in range(1, num + 1):
    fact = fact * i
print(fact)

# Question 9: Find the greatest common divisor (GCD) of 48 and 36
A = 48
B = 36
import math
GCD = math.gcd(48, 36)
print(GCD)

# Question 10: Calculate the sum of first 20 odd numbers
sum = 0
for i in range(1,40,2):
    sum += i
print(sum)